apiVersion: v1
kind: LimitRange
metadata:
  name: pg-chaos-lab-limits
  namespace: pg-chaos-lab
spec:
  limits:
    - type: Container
      default:
        cpu: "1"
        memory: 1Gi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
